### ISSUE TITLE
运行例子

### ISSUE THREAD

**Issue by YTLogos** [BioEpi/DLR_ICF#1]
@BenxiaHu 感谢你开发的这个工具，我在使用过程中发现很多问题，您这边可以提供一个运行例子吗？

**Comment by BenxiaHu** [comment]
Please post your questions here.

**Comment by YTLogos** [comment]
```
DLR_ICF_main -b -I "/mnt/e"  -f H-CK-076 -d 1000000 -r 10000 -o H-CK-076.1Mb_test_10kb -O "/mnt/e" -c ZS97.chrom.sizes
```

files in /mnt/e  dir
```
H-CK-076.mcool
ZS97.chrom.sizes
```
###Parameters:
Namespace(balanced=False, inputpath='/mnt/e', filename='H-CK-076', distance=1000000, resolution=10000, outpath='/mnt/e', chrsize='ZS97.chrom.sizes', outfile='H-CK-076.1Mb_test_10kb')
###Parameters
Traceback (most recent call last):
  File "/mnt/c/soft/miniconda3/bin/DLR_ICF_main", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/c/soft/miniconda3/lib/python3.12/site-packages/DLR_ICF/DLR_ICF_main.py", line 135, in main
    annotation(args.balanced,args.inputpath,args.filename,args.distance,args.resolution,args.outpath,args.chrsize,args.outfile,args.version)
                                                                                                                               ^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'version'

**Comment by BenxiaHu** [comment]
I just fixed that issue. you can try to download and reinstall the updated version.

**Comment by YTLogos** [comment]
I have cloned the repo to my PC, the issue is not fixed.
```
python DLR_ICF_main.py -b -I /mnt/e -f H-CK-076 -d 3000000 -r 10000 -O /mnt/e -c ../../ZS97.chrom.sizes -o test
```
###Parameters:
Namespace(balanced=False, inputpath='/mnt/e', filename='H-CK-076', distance=3000000, resolution=10000, outpath='/mnt/e', chrsize='../../ZS97.chrom.sizes', outfile='test')
###Parameters
Traceback (most recent call last):
  File "/mnt/e/DLR_ICF/DLR_ICF/DLR_ICF_main.py", line 138, in <module>
    main()
  File "/mnt/e/DLR_ICF/DLR_ICF/DLR_ICF_main.py", line 135, in main
    annotation(args.balanced,args.inputpath,args.filename,args.distance,args.resolution,args.outpath,args.chrsize,args.outfile,args.version)
                                                                                                                               ^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'version'

**Comment by BenxiaHu** [comment]
please use pip to install it:

https://pypi.org/project/DLR-ICF/1.0.6/

or 
https://anaconda.org/bxhu/dlr_icf

**Comment by YTLogos** [comment]
@BenxiaHu 最新版计算出来的ICF和DLR为啥是负值？

**Comment by BenxiaHu** [comment]
I used log2(DLR) or log2(ICF).
